### PR TITLE
Refactor c++ simple demo

### PR DESCRIPTION
**Pull request by sdtv9507**
Refactor c++ simple demo similar to the c one. I started by separating c++ sources from project files. Then SConstruct was edited to be similar to the one from the c demos and yo account for the new folder structure. Finally i added godot-cpp as a submodule and updated the project's files

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
This is great, thanks for the work you did on this!

This is not quite 100% of the way there, but I can fix up the parts that aren't working.

**Comment by BastiaanOlij** [comment]
@aaronfranke don't forget to remove the `godot_headers` submodule now that it is a nested submodule under `godot-cpp`

**Comment by aaronfranke** [comment]
@BastiaanOlij What do you mean? I don't see it in the modules file: https://github.com/godotengine/gdnative-demos/blob/master/.gitmodules

**Comment by BastiaanOlij** [comment]
@aaronfranke UGH, my bad, I forgot that the C and CPP demos are all together, didn't see it was included just for the C example :)

**Pull request merged**
