### PR TITLE
[WIP] GDNative module with procedural textures

### PR DESCRIPTION
**Pull request by BastiaanOlij**
For now it just has a Worley noise texture:
https://en.wikipedia.org/wiki/Worley_noise

Planning to add other types in due course as well

### CODE REVIEW

**Comment by karroffel** [comment]
That is cool, awesome! Will you do further work on this PR or should I merge and you open new PRs later on?

**Comment by BastiaanOlij** [comment]
I'll be adding some more changes to this. I'll change the title to WIP for now :)
I want to add a perlin noise one and maybe one or two others.
I'm also thinking about an approach to better utilize the channels. I can see a use case that you want to say "red is worley", "green is perlin", "blue is a combination of a few octaves", etc.  Though that may be a future thing.. :) 

Finally it requires control over the random seed if you want the noise to be reproducable.

**Comment by BastiaanOlij** [comment]
(ps, code review and suggestions are welcome, I'm using older gdnative techniques here)

**Comment by BastiaanOlij** [comment]
ok, split a bunch of logic out and added simplex noise.

There is a weird bug in getting the wrong parameter values one the second call to worley_texture
Also want to add better functions for combining results

**Comment by aaronfranke** [comment]
Is this still desired? If so, this may need significant work as this PR is quite old.

**Pull request closed without merging**
